Update Dockerfile and devcontainer.json
 removed some tasks done by make all-devel, currently using root user for playwright installation

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -15,15 +15,15 @@ RUN apt-get update \
         python3 \
         python3-pip \
         python3-venv \
+        python-is-python3 \
         gnupg \
         curl\
         pkg-config\
         unixodbc-dev \
         graphviz \
         libgvc6 \
-        protobuf-compiler \
-        libmysqlclient-dev \
-    && rm -rf /var/lib/apt/lists/*
+        protobuf-compiler \   
+        && rm -rf /var/lib/apt/lists/*
 
 # Add the repository for protobuf
 RUN echo "deb http://ppa.launchpad.net/maarten-fonville/protobuf/ubuntu trusty main" | tee /etc/apt/sources.list.d/protobuf.list \
@@ -35,10 +35,15 @@ RUN echo "deb http://ppa.launchpad.net/maarten-fonville/protobuf/ubuntu trusty m
 # Install pre-commit
 RUN pip install pre-commit
 
-# Create a non-root user 'streamlit'
-RUN useradd -m -s /bin/bash streamlit
-RUN chown -R streamlit:streamlit $WORKSPACE
-USER streamlit
+ARG USERNAME=streamlit
+# ARG USER_UID=1000
+# ARG USER_GID=$USER_UID
+
+# Create the user
+# RUN groupadd --gid $USER_GID $USERNAME \
+    # && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
+RUN useradd -m -s /bin/bash ${USERNAME} \
+    && chown -R $USERNAME:$USERNAME $WORKSPACE
 
 # The entry point is set to bash. Specific commands can be run via devcontainer.json
-CMD ["/bin/bash"]
+SHELL ["/bin/bash", "--login", "-eo", "pipefail", "-c"]
